### ISSUE TITLE
G5 receiver support

### ISSUE THREAD

**Issue by loudnate** [bewest/decoding-dexcom#9]
I haven't dug into this yet.

```
$ atomicaps use dexcom glucose
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/src/openaps/bin/openaps-use", line 63, in <module>
    app( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 44, in __call__
    self.run(self.args)
  File "/root/src/openaps/bin/openaps-use", line 57, in run
    output = app(args, self)
  File "/root/src/openaps/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/root/src/openaps/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/root/src/openaps/openaps/uses/use.py", line 26, in __call__
    output = self.main(args, app)
  File "/root/src/openaps/openaps/vendors/dexcom.py", line 67, in main
    records = self.dexcom.ReadRecords('EGV_DATA')
  File "/usr/local/lib/python2.7/dist-packages/dexcom_reader-0.0.7-py2.7.egg/dexcom_reader/readdata.py", line 262, in ReadRecords
    records.extend(self.ReadDatabasePage(record_type, x))
  File "/usr/local/lib/python2.7/dist-packages/dexcom_reader-0.0.7-py2.7.egg/dexcom_reader/readdata.py", line 228, in GenericRecordYielder
    yield record_type.Create(data, x)
  File "/usr/local/lib/python2.7/dist-packages/dexcom_reader-0.0.7-py2.7.egg/dexcom_reader/database_records.py", line 60, in Create
    return cls(unpacked_data, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/dexcom_reader-0.0.7-py2.7.egg/dexcom_reader/database_records.py", line 42, in __init__
    self.check_crc()
  File "/usr/local/lib/python2.7/dist-packages/dexcom_reader-0.0.7-py2.7.egg/dexcom_reader/database_records.py", line 47, in check_crc
    raise constants.CrcError('Could not parse %s' % self.__class__.__name__)
dexcom_reader.constants.CrcError: Could not parse EGVRecord
```

**Comment by bewest** [comment]
Interesting.... it's still connecting and transferring some data!? That's encouraging, at least.

**Comment by loudnate** [comment]
Closing this issue as it belongs in dexcom_reader.

**Comment by loudnate** [comment]
https://github.com/bewest/dexcom_reader/pull/1
